# Generated by Django 4.0.4 on 2023-09-20 01:28

from django.db import migrations, models
import documentos.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_alter_documento_arquivo_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo_pdf',
            field=models.FileField(upload_to='media/', validators=[documentos.models.validate_pdf]),
        ),
    ]
