# Generated by Django 4.0.4 on 2023-09-21 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_alter_documento_arquivo_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=200)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.documento')),
            ],
        ),
    ]
