# Generated by Django 4.0.4 on 2023-09-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='document',
            new_name='documento',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='term',
            new_name='termo',
        ),
        migrations.AddField(
            model_name='token',
            name='quantidade',
            field=models.BigIntegerField(default=0),
        ),
    ]
