# Generated by Django 4.0.4 on 2023-10-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_rename_document_token_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='quantidade',
            field=models.BigIntegerField(default=1),
        ),
    ]
