# Generated by Django 4.0.4 on 2023-10-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0009_alter_token_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tamanho',
            field=models.BigIntegerField(default=1),
        ),
    ]
